package com.pms.mapper;

import com.pms.po.empAccess;
import com.pms.po.empAccessExample;
import com.pms.po.empAccessKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface empAccessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_access
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    long countByExample(empAccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_access
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    int deleteByExample(empAccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_access
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    int deleteByPrimaryKey(empAccessKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_access
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    int insert(empAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_access
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    int insertSelective(empAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_access
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    List<empAccess> selectByExample(empAccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_access
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    empAccess selectByPrimaryKey(empAccessKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_access
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") empAccess record, @Param("example") empAccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_access
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    int updateByExample(@Param("record") empAccess record, @Param("example") empAccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_access
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    int updateByPrimaryKeySelective(empAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_access
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    int updateByPrimaryKey(empAccess record);
}