package com.pms.mapper;

import com.pms.po.Empwarining;
import com.pms.po.EmpwariningExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmpwariningMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empwarning
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    long countByExample(EmpwariningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empwarning
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    int deleteByExample(EmpwariningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empwarning
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    int deleteByPrimaryKey(Integer e_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empwarning
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    int insert(Empwarining record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empwarning
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    int insertSelective(Empwarining record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empwarning
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    List<Empwarining> selectByExample(EmpwariningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empwarning
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    Empwarining selectByPrimaryKey(Integer e_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empwarning
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") Empwarining record, @Param("example") EmpwariningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empwarning
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    int updateByExample(@Param("record") Empwarining record, @Param("example") EmpwariningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empwarning
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    int updateByPrimaryKeySelective(Empwarining record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empwarning
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    int updateByPrimaryKey(Empwarining record);
}