package com.pms.mapper;

import com.pms.po.SalaryLevel;
import com.pms.po.SalaryLevelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SalaryLevelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salarylevel
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    long countByExample(SalaryLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salarylevel
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    int deleteByExample(SalaryLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salarylevel
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    int deleteByPrimaryKey(Integer salary_level);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salarylevel
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    int insert(SalaryLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salarylevel
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    int insertSelective(SalaryLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salarylevel
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    List<SalaryLevel> selectByExample(SalaryLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salarylevel
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    SalaryLevel selectByPrimaryKey(Integer salary_level);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salarylevel
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") SalaryLevel record, @Param("example") SalaryLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salarylevel
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    int updateByExample(@Param("record") SalaryLevel record, @Param("example") SalaryLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salarylevel
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    int updateByPrimaryKeySelective(SalaryLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salarylevel
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    int updateByPrimaryKey(SalaryLevel record);
}