package com.pms.po;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.d_id
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    private Integer d_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.d_name
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    private String d_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.d_id
     *
     * @return the value of department.d_id
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public Integer getD_id() {
        return d_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.d_id
     *
     * @param d_id the value for department.d_id
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public void setD_id(Integer d_id) {
        this.d_id = d_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.d_name
     *
     * @return the value of department.d_name
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public String getD_name() {
        return d_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.d_name
     *
     * @param d_name the value for department.d_name
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public void setD_name(String d_name) {
        this.d_name = d_name == null ? null : d_name.trim();
    }
}