package com.pms.po;

import java.util.Date;

public class empAccessKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_access.e_id
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    private Integer e_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_access.a_id
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    private Integer a_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_access.access_date
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    private Date access_date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_access.e_id
     *
     * @return the value of emp_access.e_id
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public Integer getE_id() {
        return e_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_access.e_id
     *
     * @param e_id the value for emp_access.e_id
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public void setE_id(Integer e_id) {
        this.e_id = e_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_access.a_id
     *
     * @return the value of emp_access.a_id
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public Integer getA_id() {
        return a_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_access.a_id
     *
     * @param a_id the value for emp_access.a_id
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public void setA_id(Integer a_id) {
        this.a_id = a_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_access.access_date
     *
     * @return the value of emp_access.access_date
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public Date getAccess_date() {
        return access_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_access.access_date
     *
     * @param access_date the value for emp_access.access_date
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public void setAccess_date(Date access_date) {
        this.access_date = access_date;
    }
}