package com.pms.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class empAccessExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table emp_access
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table emp_access
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table emp_access
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_access
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public empAccessExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_access
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_access
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_access
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_access
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_access
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_access
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_access
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_access
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_access
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_access
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table emp_access
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andE_idIsNull() {
            addCriterion("e_id is null");
            return (Criteria) this;
        }

        public Criteria andE_idIsNotNull() {
            addCriterion("e_id is not null");
            return (Criteria) this;
        }

        public Criteria andE_idEqualTo(Integer value) {
            addCriterion("e_id =", value, "e_id");
            return (Criteria) this;
        }

        public Criteria andE_idNotEqualTo(Integer value) {
            addCriterion("e_id <>", value, "e_id");
            return (Criteria) this;
        }

        public Criteria andE_idGreaterThan(Integer value) {
            addCriterion("e_id >", value, "e_id");
            return (Criteria) this;
        }

        public Criteria andE_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("e_id >=", value, "e_id");
            return (Criteria) this;
        }

        public Criteria andE_idLessThan(Integer value) {
            addCriterion("e_id <", value, "e_id");
            return (Criteria) this;
        }

        public Criteria andE_idLessThanOrEqualTo(Integer value) {
            addCriterion("e_id <=", value, "e_id");
            return (Criteria) this;
        }

        public Criteria andE_idIn(List<Integer> values) {
            addCriterion("e_id in", values, "e_id");
            return (Criteria) this;
        }

        public Criteria andE_idNotIn(List<Integer> values) {
            addCriterion("e_id not in", values, "e_id");
            return (Criteria) this;
        }

        public Criteria andE_idBetween(Integer value1, Integer value2) {
            addCriterion("e_id between", value1, value2, "e_id");
            return (Criteria) this;
        }

        public Criteria andE_idNotBetween(Integer value1, Integer value2) {
            addCriterion("e_id not between", value1, value2, "e_id");
            return (Criteria) this;
        }

        public Criteria andA_idIsNull() {
            addCriterion("a_id is null");
            return (Criteria) this;
        }

        public Criteria andA_idIsNotNull() {
            addCriterion("a_id is not null");
            return (Criteria) this;
        }

        public Criteria andA_idEqualTo(Integer value) {
            addCriterion("a_id =", value, "a_id");
            return (Criteria) this;
        }

        public Criteria andA_idNotEqualTo(Integer value) {
            addCriterion("a_id <>", value, "a_id");
            return (Criteria) this;
        }

        public Criteria andA_idGreaterThan(Integer value) {
            addCriterion("a_id >", value, "a_id");
            return (Criteria) this;
        }

        public Criteria andA_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("a_id >=", value, "a_id");
            return (Criteria) this;
        }

        public Criteria andA_idLessThan(Integer value) {
            addCriterion("a_id <", value, "a_id");
            return (Criteria) this;
        }

        public Criteria andA_idLessThanOrEqualTo(Integer value) {
            addCriterion("a_id <=", value, "a_id");
            return (Criteria) this;
        }

        public Criteria andA_idIn(List<Integer> values) {
            addCriterion("a_id in", values, "a_id");
            return (Criteria) this;
        }

        public Criteria andA_idNotIn(List<Integer> values) {
            addCriterion("a_id not in", values, "a_id");
            return (Criteria) this;
        }

        public Criteria andA_idBetween(Integer value1, Integer value2) {
            addCriterion("a_id between", value1, value2, "a_id");
            return (Criteria) this;
        }

        public Criteria andA_idNotBetween(Integer value1, Integer value2) {
            addCriterion("a_id not between", value1, value2, "a_id");
            return (Criteria) this;
        }

        public Criteria andAccess_dateIsNull() {
            addCriterion("access_date is null");
            return (Criteria) this;
        }

        public Criteria andAccess_dateIsNotNull() {
            addCriterion("access_date is not null");
            return (Criteria) this;
        }

        public Criteria andAccess_dateEqualTo(Date value) {
            addCriterionForJDBCDate("access_date =", value, "access_date");
            return (Criteria) this;
        }

        public Criteria andAccess_dateNotEqualTo(Date value) {
            addCriterionForJDBCDate("access_date <>", value, "access_date");
            return (Criteria) this;
        }

        public Criteria andAccess_dateGreaterThan(Date value) {
            addCriterionForJDBCDate("access_date >", value, "access_date");
            return (Criteria) this;
        }

        public Criteria andAccess_dateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("access_date >=", value, "access_date");
            return (Criteria) this;
        }

        public Criteria andAccess_dateLessThan(Date value) {
            addCriterionForJDBCDate("access_date <", value, "access_date");
            return (Criteria) this;
        }

        public Criteria andAccess_dateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("access_date <=", value, "access_date");
            return (Criteria) this;
        }

        public Criteria andAccess_dateIn(List<Date> values) {
            addCriterionForJDBCDate("access_date in", values, "access_date");
            return (Criteria) this;
        }

        public Criteria andAccess_dateNotIn(List<Date> values) {
            addCriterionForJDBCDate("access_date not in", values, "access_date");
            return (Criteria) this;
        }

        public Criteria andAccess_dateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("access_date between", value1, value2, "access_date");
            return (Criteria) this;
        }

        public Criteria andAccess_dateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("access_date not between", value1, value2, "access_date");
            return (Criteria) this;
        }

        public Criteria andScoreIsNull() {
            addCriterion("score is null");
            return (Criteria) this;
        }

        public Criteria andScoreIsNotNull() {
            addCriterion("score is not null");
            return (Criteria) this;
        }

        public Criteria andScoreEqualTo(Double value) {
            addCriterion("score =", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotEqualTo(Double value) {
            addCriterion("score <>", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThan(Double value) {
            addCriterion("score >", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThanOrEqualTo(Double value) {
            addCriterion("score >=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThan(Double value) {
            addCriterion("score <", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThanOrEqualTo(Double value) {
            addCriterion("score <=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreIn(List<Double> values) {
            addCriterion("score in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotIn(List<Double> values) {
            addCriterion("score not in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreBetween(Double value1, Double value2) {
            addCriterion("score between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotBetween(Double value1, Double value2) {
            addCriterion("score not between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andManager_idIsNull() {
            addCriterion("manager_id is null");
            return (Criteria) this;
        }

        public Criteria andManager_idIsNotNull() {
            addCriterion("manager_id is not null");
            return (Criteria) this;
        }

        public Criteria andManager_idEqualTo(Integer value) {
            addCriterion("manager_id =", value, "manager_id");
            return (Criteria) this;
        }

        public Criteria andManager_idNotEqualTo(Integer value) {
            addCriterion("manager_id <>", value, "manager_id");
            return (Criteria) this;
        }

        public Criteria andManager_idGreaterThan(Integer value) {
            addCriterion("manager_id >", value, "manager_id");
            return (Criteria) this;
        }

        public Criteria andManager_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("manager_id >=", value, "manager_id");
            return (Criteria) this;
        }

        public Criteria andManager_idLessThan(Integer value) {
            addCriterion("manager_id <", value, "manager_id");
            return (Criteria) this;
        }

        public Criteria andManager_idLessThanOrEqualTo(Integer value) {
            addCriterion("manager_id <=", value, "manager_id");
            return (Criteria) this;
        }

        public Criteria andManager_idIn(List<Integer> values) {
            addCriterion("manager_id in", values, "manager_id");
            return (Criteria) this;
        }

        public Criteria andManager_idNotIn(List<Integer> values) {
            addCriterion("manager_id not in", values, "manager_id");
            return (Criteria) this;
        }

        public Criteria andManager_idBetween(Integer value1, Integer value2) {
            addCriterion("manager_id between", value1, value2, "manager_id");
            return (Criteria) this;
        }

        public Criteria andManager_idNotBetween(Integer value1, Integer value2) {
            addCriterion("manager_id not between", value1, value2, "manager_id");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table emp_access
     *
     * @mbg.generated do_not_delete_during_merge Thu Nov 28 15:10:10 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table emp_access
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}