package com.pms.po;

public class empAccess extends empAccessKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_access.score
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    private Double score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_access.manager_id
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    private Integer manager_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_access.score
     *
     * @return the value of emp_access.score
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_access.score
     *
     * @param score the value for emp_access.score
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_access.manager_id
     *
     * @return the value of emp_access.manager_id
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public Integer getManager_id() {
        return manager_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_access.manager_id
     *
     * @param manager_id the value for emp_access.manager_id
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public void setManager_id(Integer manager_id) {
        this.manager_id = manager_id;
    }
}