package com.pms.po;

import java.util.Date;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.e_id
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    private Integer e_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.e_name
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    private String e_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.e_sex
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    private String e_sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.e_birthday
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    private Date e_birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.e_entryDate
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    private Date e_entryDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.e_departmentid
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    private Integer e_departmentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.e_salarylevel
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    private Integer e_salarylevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.e_firewarning
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    private String e_firewarning;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.e_id
     *
     * @return the value of employee.e_id
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public Integer getE_id() {
        return e_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.e_id
     *
     * @param e_id the value for employee.e_id
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public void setE_id(Integer e_id) {
        this.e_id = e_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.e_name
     *
     * @return the value of employee.e_name
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public String getE_name() {
        return e_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.e_name
     *
     * @param e_name the value for employee.e_name
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public void setE_name(String e_name) {
        this.e_name = e_name == null ? null : e_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.e_sex
     *
     * @return the value of employee.e_sex
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public String getE_sex() {
        return e_sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.e_sex
     *
     * @param e_sex the value for employee.e_sex
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public void setE_sex(String e_sex) {
        this.e_sex = e_sex == null ? null : e_sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.e_birthday
     *
     * @return the value of employee.e_birthday
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public Date getE_birthday() {
        return e_birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.e_birthday
     *
     * @param e_birthday the value for employee.e_birthday
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public void setE_birthday(Date e_birthday) {
        this.e_birthday = e_birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.e_entryDate
     *
     * @return the value of employee.e_entryDate
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public Date getE_entryDate() {
        return e_entryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.e_entryDate
     *
     * @param e_entryDate the value for employee.e_entryDate
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public void setE_entryDate(Date e_entryDate) {
        this.e_entryDate = e_entryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.e_departmentid
     *
     * @return the value of employee.e_departmentid
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public Integer getE_departmentid() {
        return e_departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.e_departmentid
     *
     * @param e_departmentid the value for employee.e_departmentid
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public void setE_departmentid(Integer e_departmentid) {
        this.e_departmentid = e_departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.e_salarylevel
     *
     * @return the value of employee.e_salarylevel
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public Integer getE_salarylevel() {
        return e_salarylevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.e_salarylevel
     *
     * @param e_salarylevel the value for employee.e_salarylevel
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public void setE_salarylevel(Integer e_salarylevel) {
        this.e_salarylevel = e_salarylevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.e_firewarning
     *
     * @return the value of employee.e_firewarning
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public String getE_firewarning() {
        return e_firewarning;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.e_firewarning
     *
     * @param e_firewarning the value for employee.e_firewarning
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public void setE_firewarning(String e_firewarning) {
        this.e_firewarning = e_firewarning == null ? null : e_firewarning.trim();
    }
}