package com.pms.po;

import java.util.ArrayList;
import java.util.List;

public class EmpwariningExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table empwarning
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table empwarning
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table empwarning
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empwarning
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public EmpwariningExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empwarning
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empwarning
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empwarning
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empwarning
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empwarning
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empwarning
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empwarning
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empwarning
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empwarning
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empwarning
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table empwarning
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andE_idIsNull() {
            addCriterion("e_id is null");
            return (Criteria) this;
        }

        public Criteria andE_idIsNotNull() {
            addCriterion("e_id is not null");
            return (Criteria) this;
        }

        public Criteria andE_idEqualTo(Integer value) {
            addCriterion("e_id =", value, "e_id");
            return (Criteria) this;
        }

        public Criteria andE_idNotEqualTo(Integer value) {
            addCriterion("e_id <>", value, "e_id");
            return (Criteria) this;
        }

        public Criteria andE_idGreaterThan(Integer value) {
            addCriterion("e_id >", value, "e_id");
            return (Criteria) this;
        }

        public Criteria andE_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("e_id >=", value, "e_id");
            return (Criteria) this;
        }

        public Criteria andE_idLessThan(Integer value) {
            addCriterion("e_id <", value, "e_id");
            return (Criteria) this;
        }

        public Criteria andE_idLessThanOrEqualTo(Integer value) {
            addCriterion("e_id <=", value, "e_id");
            return (Criteria) this;
        }

        public Criteria andE_idIn(List<Integer> values) {
            addCriterion("e_id in", values, "e_id");
            return (Criteria) this;
        }

        public Criteria andE_idNotIn(List<Integer> values) {
            addCriterion("e_id not in", values, "e_id");
            return (Criteria) this;
        }

        public Criteria andE_idBetween(Integer value1, Integer value2) {
            addCriterion("e_id between", value1, value2, "e_id");
            return (Criteria) this;
        }

        public Criteria andE_idNotBetween(Integer value1, Integer value2) {
            addCriterion("e_id not between", value1, value2, "e_id");
            return (Criteria) this;
        }

        public Criteria andWarning_timesIsNull() {
            addCriterion("warning_times is null");
            return (Criteria) this;
        }

        public Criteria andWarning_timesIsNotNull() {
            addCriterion("warning_times is not null");
            return (Criteria) this;
        }

        public Criteria andWarning_timesEqualTo(Integer value) {
            addCriterion("warning_times =", value, "warning_times");
            return (Criteria) this;
        }

        public Criteria andWarning_timesNotEqualTo(Integer value) {
            addCriterion("warning_times <>", value, "warning_times");
            return (Criteria) this;
        }

        public Criteria andWarning_timesGreaterThan(Integer value) {
            addCriterion("warning_times >", value, "warning_times");
            return (Criteria) this;
        }

        public Criteria andWarning_timesGreaterThanOrEqualTo(Integer value) {
            addCriterion("warning_times >=", value, "warning_times");
            return (Criteria) this;
        }

        public Criteria andWarning_timesLessThan(Integer value) {
            addCriterion("warning_times <", value, "warning_times");
            return (Criteria) this;
        }

        public Criteria andWarning_timesLessThanOrEqualTo(Integer value) {
            addCriterion("warning_times <=", value, "warning_times");
            return (Criteria) this;
        }

        public Criteria andWarning_timesIn(List<Integer> values) {
            addCriterion("warning_times in", values, "warning_times");
            return (Criteria) this;
        }

        public Criteria andWarning_timesNotIn(List<Integer> values) {
            addCriterion("warning_times not in", values, "warning_times");
            return (Criteria) this;
        }

        public Criteria andWarning_timesBetween(Integer value1, Integer value2) {
            addCriterion("warning_times between", value1, value2, "warning_times");
            return (Criteria) this;
        }

        public Criteria andWarning_timesNotBetween(Integer value1, Integer value2) {
            addCriterion("warning_times not between", value1, value2, "warning_times");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table empwarning
     *
     * @mbg.generated do_not_delete_during_merge Thu Nov 28 15:10:10 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table empwarning
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}