package com.pms.po;

public class Empwarining {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empwarning.e_id
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    private Integer e_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empwarning.warning_times
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    private Integer warning_times;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empwarning.e_id
     *
     * @return the value of empwarning.e_id
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public Integer getE_id() {
        return e_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empwarning.e_id
     *
     * @param e_id the value for empwarning.e_id
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public void setE_id(Integer e_id) {
        this.e_id = e_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empwarning.warning_times
     *
     * @return the value of empwarning.warning_times
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public Integer getWarning_times() {
        return warning_times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empwarning.warning_times
     *
     * @param warning_times the value for empwarning.warning_times
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public void setWarning_times(Integer warning_times) {
        this.warning_times = warning_times;
    }
}