package com.pms.po;

public class Manager {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.u_id
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    private Integer u_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.u_name
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    private String u_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.u_password
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    private String u_password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.u_category
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    private String u_category;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.u_id
     *
     * @return the value of manager.u_id
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public Integer getU_id() {
        return u_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.u_id
     *
     * @param u_id the value for manager.u_id
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public void setU_id(Integer u_id) {
        this.u_id = u_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.u_name
     *
     * @return the value of manager.u_name
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public String getU_name() {
        return u_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.u_name
     *
     * @param u_name the value for manager.u_name
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public void setU_name(String u_name) {
        this.u_name = u_name == null ? null : u_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.u_password
     *
     * @return the value of manager.u_password
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public String getU_password() {
        return u_password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.u_password
     *
     * @param u_password the value for manager.u_password
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public void setU_password(String u_password) {
        this.u_password = u_password == null ? null : u_password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.u_category
     *
     * @return the value of manager.u_category
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public String getU_category() {
        return u_category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.u_category
     *
     * @param u_category the value for manager.u_category
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public void setU_category(String u_category) {
        this.u_category = u_category == null ? null : u_category.trim();
    }
}