package com.pms.po;

public class SalaryLevel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salarylevel.salary_level
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    private Integer salary_level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salarylevel.base_salary
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    private Double base_salary;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salarylevel.salary_level
     *
     * @return the value of salarylevel.salary_level
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public Integer getSalary_level() {
        return salary_level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salarylevel.salary_level
     *
     * @param salary_level the value for salarylevel.salary_level
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public void setSalary_level(Integer salary_level) {
        this.salary_level = salary_level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salarylevel.base_salary
     *
     * @return the value of salarylevel.base_salary
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public Double getBase_salary() {
        return base_salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salarylevel.base_salary
     *
     * @param base_salary the value for salarylevel.base_salary
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public void setBase_salary(Double base_salary) {
        this.base_salary = base_salary;
    }
}