package com.pms.po;

import java.util.Date;

public class Salary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.e_id
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    private Integer e_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.attendance_salary
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    private Double attendance_salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.achievement_salary
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    private Double achievement_salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.benefit_salary
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    private Double benefit_salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.s_salary
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    private Double s_salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.s_date
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    private Date s_date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.e_id
     *
     * @return the value of salary.e_id
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public Integer getE_id() {
        return e_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.e_id
     *
     * @param e_id the value for salary.e_id
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public void setE_id(Integer e_id) {
        this.e_id = e_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.attendance_salary
     *
     * @return the value of salary.attendance_salary
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public Double getAttendance_salary() {
        return attendance_salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.attendance_salary
     *
     * @param attendance_salary the value for salary.attendance_salary
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public void setAttendance_salary(Double attendance_salary) {
        this.attendance_salary = attendance_salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.achievement_salary
     *
     * @return the value of salary.achievement_salary
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public Double getAchievement_salary() {
        return achievement_salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.achievement_salary
     *
     * @param achievement_salary the value for salary.achievement_salary
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public void setAchievement_salary(Double achievement_salary) {
        this.achievement_salary = achievement_salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.benefit_salary
     *
     * @return the value of salary.benefit_salary
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public Double getBenefit_salary() {
        return benefit_salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.benefit_salary
     *
     * @param benefit_salary the value for salary.benefit_salary
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public void setBenefit_salary(Double benefit_salary) {
        this.benefit_salary = benefit_salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.s_salary
     *
     * @return the value of salary.s_salary
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public Double getS_salary() {
        return s_salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.s_salary
     *
     * @param s_salary the value for salary.s_salary
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public void setS_salary(Double s_salary) {
        this.s_salary = s_salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.s_date
     *
     * @return the value of salary.s_date
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public Date getS_date() {
        return s_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.s_date
     *
     * @param s_date the value for salary.s_date
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public void setS_date(Date s_date) {
        this.s_date = s_date;
    }
}