package com.pms.po;

import java.util.ArrayList;
import java.util.List;

public class SalaryLevelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table salarylevel
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table salarylevel
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table salarylevel
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salarylevel
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public SalaryLevelExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salarylevel
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salarylevel
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salarylevel
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salarylevel
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salarylevel
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salarylevel
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salarylevel
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salarylevel
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salarylevel
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salarylevel
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table salarylevel
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSalary_levelIsNull() {
            addCriterion("salary_level is null");
            return (Criteria) this;
        }

        public Criteria andSalary_levelIsNotNull() {
            addCriterion("salary_level is not null");
            return (Criteria) this;
        }

        public Criteria andSalary_levelEqualTo(Integer value) {
            addCriterion("salary_level =", value, "salary_level");
            return (Criteria) this;
        }

        public Criteria andSalary_levelNotEqualTo(Integer value) {
            addCriterion("salary_level <>", value, "salary_level");
            return (Criteria) this;
        }

        public Criteria andSalary_levelGreaterThan(Integer value) {
            addCriterion("salary_level >", value, "salary_level");
            return (Criteria) this;
        }

        public Criteria andSalary_levelGreaterThanOrEqualTo(Integer value) {
            addCriterion("salary_level >=", value, "salary_level");
            return (Criteria) this;
        }

        public Criteria andSalary_levelLessThan(Integer value) {
            addCriterion("salary_level <", value, "salary_level");
            return (Criteria) this;
        }

        public Criteria andSalary_levelLessThanOrEqualTo(Integer value) {
            addCriterion("salary_level <=", value, "salary_level");
            return (Criteria) this;
        }

        public Criteria andSalary_levelIn(List<Integer> values) {
            addCriterion("salary_level in", values, "salary_level");
            return (Criteria) this;
        }

        public Criteria andSalary_levelNotIn(List<Integer> values) {
            addCriterion("salary_level not in", values, "salary_level");
            return (Criteria) this;
        }

        public Criteria andSalary_levelBetween(Integer value1, Integer value2) {
            addCriterion("salary_level between", value1, value2, "salary_level");
            return (Criteria) this;
        }

        public Criteria andSalary_levelNotBetween(Integer value1, Integer value2) {
            addCriterion("salary_level not between", value1, value2, "salary_level");
            return (Criteria) this;
        }

        public Criteria andBase_salaryIsNull() {
            addCriterion("base_salary is null");
            return (Criteria) this;
        }

        public Criteria andBase_salaryIsNotNull() {
            addCriterion("base_salary is not null");
            return (Criteria) this;
        }

        public Criteria andBase_salaryEqualTo(Double value) {
            addCriterion("base_salary =", value, "base_salary");
            return (Criteria) this;
        }

        public Criteria andBase_salaryNotEqualTo(Double value) {
            addCriterion("base_salary <>", value, "base_salary");
            return (Criteria) this;
        }

        public Criteria andBase_salaryGreaterThan(Double value) {
            addCriterion("base_salary >", value, "base_salary");
            return (Criteria) this;
        }

        public Criteria andBase_salaryGreaterThanOrEqualTo(Double value) {
            addCriterion("base_salary >=", value, "base_salary");
            return (Criteria) this;
        }

        public Criteria andBase_salaryLessThan(Double value) {
            addCriterion("base_salary <", value, "base_salary");
            return (Criteria) this;
        }

        public Criteria andBase_salaryLessThanOrEqualTo(Double value) {
            addCriterion("base_salary <=", value, "base_salary");
            return (Criteria) this;
        }

        public Criteria andBase_salaryIn(List<Double> values) {
            addCriterion("base_salary in", values, "base_salary");
            return (Criteria) this;
        }

        public Criteria andBase_salaryNotIn(List<Double> values) {
            addCriterion("base_salary not in", values, "base_salary");
            return (Criteria) this;
        }

        public Criteria andBase_salaryBetween(Double value1, Double value2) {
            addCriterion("base_salary between", value1, value2, "base_salary");
            return (Criteria) this;
        }

        public Criteria andBase_salaryNotBetween(Double value1, Double value2) {
            addCriterion("base_salary not between", value1, value2, "base_salary");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table salarylevel
     *
     * @mbg.generated do_not_delete_during_merge Thu Nov 28 15:10:10 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table salarylevel
     *
     * @mbg.generated Thu Nov 28 15:10:10 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}